title = "Valentin Pelloin"
baseURL = "https://vpelloin.eu"
theme = "researcher"
disableKinds = ["robotsTXT"]
enableEmoji = true

[params]
  author = "Valentin Pelloin"
  lang = "en"
  description = "Valentin Pelloin, PhD Student in Natural Language Processing (NLP), working on Spoken Language Understanding (SLU) systems."
  favicon = "favicon.ico"
  [params.footer]
    text = "Theme by Olivier Roques"
    url = "https://github.com/ojroques/hugo-researcher"
  [params.twitterCard]
    generate = true
	card = "summary"
	image = "cards/home.png"
	imageAlt = "Valentin Pelloin home card image"
	site = "@valentinp72"
	creator = "@valentinp72"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 3
  [[menu.main]]
    name = "Gallery"
	url = "/gallery"
	weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
