title = "Valentin Pelloin"
baseURL = "https://vpelloin.eu"
theme = "researcher"
disableKinds = ["taxonomy", "term", "robotsTXT"]
enableEmoji = true

[params]
  author = "Valentin Pelloin"
  lang = "en"
  description = "Valentin Pelloin, PhD Student in Natural Language Processing (NLP), working Spoken Language Understanding (SLU) systems."
  favicon = "favicon.ico"
  [params.footer]
    text = "Theme by Olivier Roques"
    url = "https://github.com/ojroques/hugo-researcher"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "Gallery"
	url = "/gallery"
	weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
